### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/password-generator#1]
## Task
- [x] button generates prompts for password criteria
- [x] prompts offer criteria options
- [x] password length prompt between 8 - 128 characters
- [x] lowercase, uppercase, numeric, and/or special character prompts
- [x] validate input and ensure one character type was selected
- [x] password is generated and matches the selected criteria
- [x] password is either displayed in an alert or on the page
